parameters:
    app.storage.directory: '%kernel.project_dir%/public/media'
    app.assets.base_url: '%env(APP_PUBLIC_URL)%/media'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $publicUrl: '%env(APP_PUBLIC_URL)%'
            string $mailFrom: '%env(MAIL_FROM)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Modules/*/Domain/'

    App\Modules\Academy\Domain\Academy\AcademyRepository: '@App\Modules\Academy\Infrastructure\Persistence\AcademyRepository'
    App\Modules\Venue\Domain\Venue\VenueRepository: '@App\Modules\Venue\Infrastructure\Persistence\VenueRepository'
    App\Modules\Category\Domain\Category\CategoryRepository: '@App\Modules\Category\Infrastructure\Persistence\CategoryRepository'
    App\Modules\Guardian\Domain\LegalGuardian\LegalGuardianRepository: '@App\Modules\Guardian\Infrastructure\Persistence\LegalGuardianRepository'
    App\Modules\Player\Domain\Player\PlayerRepository: '@App\Modules\Player\Infrastructure\Persistence\PlayerRepository'
    App\Modules\Player\Domain\PlayerGuardian\PlayerGuardianRepository: '@App\Modules\Player\Infrastructure\Persistence\PlayerGuardianRepository'
    App\Modules\Membership\Domain\Membership\MembershipRepository: '@App\Modules\Membership\Infrastructure\Persistence\MembershipRepository'
    App\Modules\PaymentConcept\Domain\PaymentConcept\PaymentConceptRepository: '@App\Modules\PaymentConcept\Infrastructure\Persistence\PaymentConceptRepository'
    App\Modules\Staff\Domain\Staff\StaffRepository: '@App\Modules\Staff\Infrastructure\Persistence\StaffRepository'
    App\Modules\Staff\Domain\TeamStaffAssignment\TeamStaffAssignmentRepository: '@App\Modules\Staff\Infrastructure\Persistence\TeamStaffAssignmentRepository'
    App\Modules\Team\Domain\Team\TeamRepository: '@App\Modules\Team\Infrastructure\Persistence\TeamRepository'
    App\Modules\TeamAssignment\Domain\TeamAssignment\TeamAssignmentRepository: '@App\Modules\TeamAssignment\Infrastructure\Persistence\TeamAssignmentRepository'
    App\Modules\Identity\Domain\Policy\UserAdministrationPolicy: ~

    # Explicits
    App\Shared\Infrastructure\EventSubscriber\DoctrineAuditSubscriber:
        tags: ['doctrine.event_subscriber']

    App\Shared\Domain\Contracts\FileStorage:
        class: App\Shared\Infrastructure\Storage\LocalStorage
        arguments:
            $targetDirectory: '%app.storage.directory%'
            $assetsBaseUrl: '%app.assets.base_url%'
