services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $publicUrl: '%env(APP_PUBLIC_URL)%'
            string $mailFrom: '%env(MAIL_FROM)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Modules/*/Domain/'

    App\Modules\Academy\Domain\Academy\AcademyRepository: '@App\Modules\Academy\Infrastructure\Persistence\AcademyRepository'
    App\Modules\Venue\Domain\Venue\VenueRepository: '@App\Modules\Venue\Infrastructure\Persistence\VenueRepository'
    App\Modules\Category\Domain\Category\CategoryRepository: '@App\Modules\Category\Infrastructure\Persistence\CategoryRepository'
    App\Modules\Player\Domain\Player\PlayerRepository: '@App\Modules\Player\Infrastructure\Persistence\PlayerRepository'
    App\Modules\Identity\Domain\Policy\UserAdministrationPolicy: ~

    # Explicits
    App\Shared\Infrastructure\Http\ProblemDetailsExceptionSubscriber:
        arguments:
            $logger: '@monolog.logger.application'
