@baseUrl = http://localhost:8081
@adminEmail = admin@playertech.com
@adminPassword = secret123
@categoryId = 019f0654-39eb-7ecd-82a1-c11ee4097cb5

### Login root success
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

> {% client.global.set("token", response.body.data.token); %}

### List categories
GET {{baseUrl}}/api/v1/academy/categories
Authorization: Bearer {{token}}
Accept: application/json

### Show category
GET {{baseUrl}}/api/v1/academy/categories/{{categoryId}}
Authorization: Bearer {{token}}
Accept: application/json

### Create category success
POST {{baseUrl}}/api/v1/academy/categories
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "category_key": "SUB_12",
  "name": "Sub-12",
  "min_age": 10,
  "max_age": 12,
  "description": "Categoría para jugadores entre 10 y 12 años."
}

### Create category error duplicate key
POST {{baseUrl}}/api/v1/academy/categories
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "category_key": "SUB_12",
  "name": "Sub-12 B",
  "min_age": 10,
  "max_age": 12,
  "description": "Intento duplicado."
}

### Update category
PUT {{baseUrl}}/api/v1/academy/categories/{{categoryId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "category_key": "SUB_13",
  "name": "Sub-13",
  "min_age": 11,
  "max_age": 13,
  "description": "Updated category"
}

### Inactivate category
PATCH {{baseUrl}}/api/v1/academy/categories/{{categoryId}}/inactivate
Authorization: Bearer {{token}}
Accept: application/json

### Activate category
PATCH {{baseUrl}}/api/v1/academy/categories/{{categoryId}}/activate
Authorization: Bearer {{token}}
Accept: application/json
