@baseUrl = http://localhost:8081
@token = {{token}}
@tenantToken = {{tenantToken}}
@academyId = {{academyId}}
@activationToken = {{activationToken}}

### List Categories
GET {{baseUrl}}/api/v1/academy/categories
Authorization: Bearer {{token}}
Accept: application/json

### Create category
### Request DTO: CreateCategoryInput

POST {{baseUrl}}/api/v1/categories
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Sub-12",
  "min_age": 10,
  "max_age": 12,
  "description": "Categoría para jugadores entre 10 y 12 años."
}

### Update Category
### Request DTO: UpdateCategoryInput

PUT {{baseUrl}}/api/v1/academy/categories/{{categoryId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sub-13",
  "minAge": 11,
  "maxAge": 13,
  "description": "Updated category"
}