@baseUrl = http://localhost:8081
@adminEmail = admin@playertech.com
@adminPassword = secret123
@playerId = {{playerId}}

### Login root success
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

> {% client.global.set("token", response.body.data.token); %}

### Create player
POST {{baseUrl}}/api/v1/academy/players
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "first_name": "Juan",
  "last_name": "Pérez",
  "birth_date": "2014-05-18",
  "document_number": "12345678"
}

### List players
GET {{baseUrl}}/api/v1/academy/players
Authorization: Bearer {{token}}
Accept: application/json

### Show player
GET {{baseUrl}}/api/v1/academy/players/{{playerId}}
Authorization: Bearer {{token}}
Accept: application/json

### Update player
PUT {{baseUrl}}/api/v1/academy/players/{{playerId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "first_name": "Juan Carlos",
  "last_name": "Pérez Gómez",
  "birth_date": "2014-05-20",
  "document_number": "87654321"
}

### Inactivate player
PATCH {{baseUrl}}/api/v1/academy/players/{{playerId}}/inactivate
Authorization: Bearer {{token}}
Accept: application/json

### Activate player
PATCH {{baseUrl}}/api/v1/academy/players/{{playerId}}/activate
Authorization: Bearer {{token}}
Accept: application/json

### Import players
POST {{baseUrl}}/api/v1/academy/players/import
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json

--boundary
Content-Disposition: form-data; name="file"; filename="players.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./fixtures/players.xlsx
--boundary--

### Import players error invalid file
POST {{baseUrl}}/api/v1/academy/players/import
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json

--boundary
Content-Disposition: form-data; name="file"; filename="players.txt"
Content-Type: text/plain

< ./fixtures/players.txt
--boundary--
