services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../app:/var/www/html
    depends_on:
      - mysql
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: mysql://playertech:playertech@mysql:3306/playertech?serverVersion=8.0&charset=utf8mb4
      JWT_PASSPHRASE: change_this_password
      MAILER_DSN: smtp://mailpit:1025
      MAIL_FROM: no-reply@playertech.local
      APP_PUBLIC_URL: http://localhost:8081
      APP_AUTH_FRONTEND_URL: http://localhost:4200
      APP_TENANT_ACTIVATION_URL: http://localhost:4200/tenant/activate

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: playertech
      MYSQL_USER: playertech
      MYSQL_PASSWORD: playertech
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
