api_v1_auth_login:
    path: /api/v1/auth/login
    methods: [POST]

shared_controllers:
    resource:
        path: ../../src/Shared/Presentation/Http/
        namespace: App\Shared\Presentation\Http
    type: attribute
    prefix: /api/v1

identity_controllers:
    resource:
        path: ../../src/Modules/Identity/Presentation/Http/
        namespace: App\Modules\Identity\Presentation\Http
    type: attribute
    prefix: /api/v1

academy_controllers:
    resource:
        path: ../../src/Modules/Academy/Presentation/Http/
        namespace: App\Modules\Academy\Presentation\Http
    type: attribute
    prefix: /api/v1

venue_controllers:
    resource:
        path: ../../src/Modules/Venue/Presentation/Http/
        namespace: App\Modules\Venue\Presentation\Http
    type: attribute
    prefix: /api/v1

category_controllers:
    resource:
        path: ../../src/Modules/Category/Presentation/Http/
        namespace: App\Modules\Category\Presentation\Http
    type: attribute
    prefix: /api/v1

player_controllers:
    resource:
        path: ../../src/Modules/Player/Presentation/Http/
        namespace: App\Modules\Player\Presentation\Http
    type: attribute
    prefix: /api/v1

guardian_controllers:
    resource:
        path: ../../src/Modules/Guardian/Presentation/Http/
        namespace: App\Modules\Guardian\Presentation\Http
    type: attribute
    prefix: /api/v1

team_controllers:
    resource:
        path: ../../src/Modules/Team/Presentation/Http/
        namespace: App\Modules\Team\Presentation\Http
    type: attribute
    prefix: /api/v1

staff_controllers:
    resource:
        path: ../../src/Modules/Staff/Presentation/Http/
        namespace: App\Modules\Staff\Presentation\Http
    type: attribute
    prefix: /api/v1
