api_v1_auth_login:
    path: /api/v1/auth/login
    methods: [POST]

shared_controllers:
    resource:
        path: ../../src/Shared/Presentation/Http/
        namespace: App\Shared\Presentation\Http
    type: attribute
    prefix: /api/v1

identity_controllers:
    resource:
        path: ../../src/Modules/Identity/Presentation/Http/
        namespace: App\Modules\Identity\Presentation\Http
    type: attribute
    prefix: /api/v1

academy_controllers:
    resource:
        path: ../../src/Modules/Academy/Presentation/Http/
        namespace: App\Modules\Academy\Presentation\Http
    type: attribute
    prefix: /api/v1