doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        types:
            academy_id: App\Modules\Academy\Infrastructure\Persistence\Doctrine\Type\AcademyIdType
            venue_id: App\Modules\Venue\Infrastructure\Persistence\Doctrine\Type\VenueIdType
    orm:
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        validate_xml_mapping: true
        filters:
            soft_delete:
                class: App\Shared\Infrastructure\Persistence\Doctrine\Filter\SoftDeleteFilter
                enabled: true
        mappings:
            Identity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/Identity/Domain/User'
                prefix: 'App\Modules\Identity\Domain\User'
                alias: Identity
            Academy:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Academy/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Academy\Domain\Academy
                alias: Academy
            Venue:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Venue/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Venue\Domain\Venue
                alias: Venue
            Shared:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Shared\Domain\ValueObject'
                alias: Shared
