doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        types:
            academy_id: App\Modules\Academy\Infrastructure\Persistence\Doctrine\Type\AcademyIdType
            venue_id: App\Modules\Venue\Infrastructure\Persistence\Doctrine\Type\VenueIdType
            category_id: App\Modules\Category\Infrastructure\Persistence\Doctrine\Type\CategoryIdType
            player_id: App\Modules\Player\Infrastructure\Persistence\Doctrine\Type\PlayerIdType
            team_id: App\Modules\Team\Infrastructure\Persistence\Doctrine\Type\TeamIdType
            legal_guardian_id: App\Modules\Guardian\Infrastructure\Persistence\Doctrine\Type\LegalGuardianIdType
            player_guardian_id: App\Modules\Player\Infrastructure\Persistence\Doctrine\Type\PlayerGuardianIdType
            membership_id: App\Modules\Membership\Infrastructure\Persistence\Doctrine\Type\MembershipIdType
            payment_concept_id: App\Modules\PaymentConcept\Infrastructure\Persistence\Doctrine\Type\PaymentConceptIdType
            staff_id: App\Modules\Staff\Infrastructure\Persistence\Doctrine\Type\StaffIdType
            team_staff_assignment_id: App\Modules\Staff\Infrastructure\Persistence\Doctrine\Type\TeamStaffAssignmentIdType
            team_assignment_id: App\Modules\TeamAssignment\Infrastructure\Persistence\Doctrine\Type\TeamAssignmentIdType
    orm:
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        validate_xml_mapping: true
        filters:
            soft_delete:
                class: App\Shared\Infrastructure\Persistence\Doctrine\Filter\SoftDeleteFilter
                enabled: true
            tenant:
                class: App\Shared\Infrastructure\Persistence\Doctrine\Filter\TenantFilter
                enabled: false
        mappings:
            Identity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/Identity/Domain/User'
                prefix: 'App\Modules\Identity\Domain\User'
                alias: Identity
            Academy:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Academy/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Academy\Domain\Academy
                alias: Academy
            Venue:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Venue/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Venue\Domain\Venue
                alias: Venue
            Category:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Category/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Category\Domain\Category
                alias: Category
            Player:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Player/Infrastructure/Persistence/Doctrine/Mapping/Player'
                prefix: App\Modules\Player\Domain\Player
                alias: Player
            PlayerGuardian:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Player/Infrastructure/Persistence/Doctrine/Mapping/PlayerGuardian'
                prefix: App\Modules\Player\Domain\PlayerGuardian
                alias: PlayerGuardian
            Team:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Team/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Team\Domain\Team
                alias: Team
            Guardian:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Guardian/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Guardian\Domain\LegalGuardian
                alias: Guardian
            Membership:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Membership/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Membership\Domain\Membership
                alias: Membership
            PaymentConcept:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/PaymentConcept/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\PaymentConcept\Domain\PaymentConcept
                alias: PaymentConcept
            Staff:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Staff/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\Staff\Domain
                alias: Staff
            TeamAssignment:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/TeamAssignment/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Modules\TeamAssignment\Domain\TeamAssignment
                alias: TeamAssignment
            Shared:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Shared\Domain\ValueObject'
                alias: Shared
