security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Modules\Identity\Domain\User\AccountUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            stateless: true
            provider: app_user_provider
            user_checker: App\Modules\Identity\Infrastructure\Security\UserChecker
            jwt: ~
            json_login:
                check_path: api_v1_auth_login
                username_path: email
                password_path: password
                success_handler: App\Modules\Identity\Infrastructure\Security\AuthenticationSuccessHandler
                failure_handler: App\Modules\Identity\Infrastructure\Security\AuthenticationFailureHandler

    access_control:
        - { path: ^/api/v1/health$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/public/tenants, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/public/users, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/me$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1/platform, roles: ROLE_ROOT }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }

